name: Danger Swift

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # 手動実行用のトリガー

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        args: --failOnErrors --no-publish-check
