name: Danger Swift

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Danger
  # https://github.com/danger/swift
  danger:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v4
      
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift:3.15.0
        with:
            args: --failOnErrors --no-publish-check --dangerfile DangerStorage/Dangerfile.swift
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

